### ISSUE TITLE
Deprecation warning comments

### ISSUE THREAD

**Issue by korenevichev** [chenjiahan/rodal#10]
* Rodal version: 1.3.2
* React version: 15.1.0

## Warnings
* You are manually calling a React.PropTypes validation function for the `width` prop on `Rodal`. This is deprecated and will not work in the next major version.
* You are manually calling a React.PropTypes validation function for the `height` prop on `Rodal`. This is deprecated and will not work in the next major version.
* You are manually calling a React.PropTypes validation function for the `onClose` prop on `Rodal`. This is deprecated and will not work in the next major version.
* You are manually calling a React.PropTypes validation function for the `visible` prop on `Rodal`. This is deprecated and will not work in the next major version. 
* You are manually calling a React.PropTypes validation function for the `showMask` prop on `Rodal`. This is deprecated and will not work in the next major version.
* You are manually calling a React.PropTypes validation function for the `showCloseButton` prop on `Rodal`. This is deprecated and will not work in the next major version. 
*You are manually calling a React.PropTypes validation function for the `animation` prop on `Rodal`. This is deprecated and will not work in the next major version.
* You are manually calling a React.PropTypes validation function for the `duration` prop on `Rodal`. This is deprecated and will not work in the next major version.
* You are manually calling a React.PropTypes validation function for the `measure` prop on `Rodal`. This is deprecated and will not work in the next major version.

**Comment by chenjiahan** [comment]
@korenevichev It seems just a bug with the react version. If you update to version 15.3.0, all the warnings will disappear.
