### ISSUE TITLE
Disable width, height attributes of Rodal

### ISSUE THREAD

**Issue by ninhva** [chenjiahan/rodal#12]
I have an issue about responsive with Rodal.

Because Rodal add width, height attributes as inline styles, it's difficult for responsive.

Can you add an attribute to disable width, height?

Thanks.

**Comment by chenjiahan** [comment]
You can add customStyles prop to override the width and height.

```javascript
const customStyles = {
    width: 'auto',
    height: 'auto'
}
```

**Comment by ninhva** [comment]
I tried and it worked, but margin attributes is incorrect

**Comment by chenjiahan** [comment]
you should override the default margin.
```javascript
const customStyles = {
    width: 'auto',
    height: 'auto',
    margin: 0
}
```
