### ISSUE TITLE
Disable modal close on clicking backdrop

### ISSUE THREAD

**Issue by ashfaqrafi** [chenjiahan/rodal#17]
I want the modal will not close while clicked on the backdrop or on pressing the esc button, I have seen some function like data-backdrop="static" data-keyboard="false" but I tried them in the Rodal but in vain, could you guys please help me out with a feasible solution?

**Comment by chenjiahan** [comment]
1. Pressing the esc button won't close the modal.
2. If you don't need a mask, you can set showMask props to false. 
    If you just want to disable the click event in mask, you can try this:

``` javascript
hide (event) {
    if (event.target.className === 'rodal-mask') {
        return;
    }
    this.setState({ visible: false });
}
```
