### ISSUE TITLE
IE9点击关闭按钮，无法关闭弹窗

### ISSUE THREAD

**Issue by rainooy** [chenjiahan/rodal#19]

**Comment by chenjiahan** [comment]
感谢反馈，该问题是由于 IE9 下不支持 animationend 事件导致的。目前正在尝试解决

**Comment by rainooy** [comment]
我试着在leave()方法判断是否为ie9，然后setState {isShow:false}，是可以实现的

**Comment by chenjiahan** [comment]
该方案可行，已在 1.4.1 版本中加入。感谢建议~
