### ISSUE TITLE
Add option to prevent closing when mask is clicked.

### ISSUE THREAD

**Issue by cniesen** [chenjiahan/rodal#21]
Provide an option that disabled closing of the Rodal when the mask is clicked.  Proposed name is closeMaskOnClick with default to be true.

This feature request is similar to the backdrop='static' option of [bootstrap modal](https://getbootstrap.com/javascript/#modals).

Meanwhile this [Stackoverflow ](https://stackoverflow.com/questions/41907756/disable-modal-backdrop-in-react-rodal) answer has a work around.

**Comment by chenjiahan** [comment]
That's a useful feature. Thanks~

**Comment by cniesen** [comment]
You're welcome.  And thanks for merging the pull request.  
Any idea when the next npm release will be done?

**Comment by chenjiahan** [comment]
version 1.5.1 has been released

**Comment by cniesen** [comment]
Super!  Thank you very much.
