### ISSUE TITLE
Add a close on ESC pressed option

### ISSUE THREAD

**Issue by githubdoramon** [chenjiahan/rodal#26]
Would be nice to be able to close the current modal in focus by pressing ESC

**Comment by chenjiahan** [comment]
@githubdoramon Thanks for your advertisement, the closeOnEsc prop has been added in version 1.5.5, please try it.

**Comment by githubdoramon** [comment]
It works @chenjiahan !!!! The only weird thing is that when I don`t set this option, I am able to focus one of my inputs (a react-select actually) when I open the modal... With the option set, the input does not get focused when I open the modal

**Comment by chenjiahan** [comment]
@githubdoramon When closeOnEsc option is set, the dialog when auto get focused after become visible. So that rodal can listen to keyUp event. That's why your input can't get focused automatically. 
If you want to keep the  input getting focused, maybe you shouldn't use the closeOnEsc prop..
