### ISSUE TITLE
closeOnEsc, showCloseButton, showMask not working

### ISSUE THREAD

**Issue by carlosjunod** [chenjiahan/rodal#28]
Hello, thanks for make this component available for everyone! great job.
my case, maybe I'm doing something wrong but the boolean configuration is not working for me for the properties closeOnEsc, showCloseButton, showMask

```
<Rodal
  width='100vw'
  height='100vh'
  visible={this.state.isModalVisible}
  onClose={this._hideModal.bind(this)}
  animation="slideDown"
  showMask="false"
  closeOnEsc="false"
  showCloseButton="false"
  customStyles={
    {
      backgroundColor: this.state.projectOpen.bg_color,
      color: this.state.projectOpen.txt_color,
      overflow: 'scroll'            
    }
  }
>
  
  <div>
    <h1>{this.state.projectOpen.title}</h1>
    {/* my content....... /*}
    </div>
</Rodal>
```

**Comment by Sprinter100** [comment]
Shouldn't it be:
showMask={false}
closeOnEsc={false}
showCloseButton={false} ?

Because you're passing values as strings, and they're not empty therefore not false.

**Comment by carlosjunod** [comment]
thanks!
