### ISSUE TITLE
leaveAnimation doesn't not work with slideDown

### ISSUE THREAD

**Issue by hayola** [chenjiahan/rodal#38]
On existing the modal, the slideDown does not seem to work.

**Comment by chenjiahan** [comment]
@hayola  Can you provide a minimal demo of the problem via https://codesandbox.io/s/pgKpvo3om ?

**Comment by hayola** [comment]
@chenjiahan I have tried to replicate the problem using the exact code I have saved in the pen. The funny thing is that it works as suppose on the pen. However, here is a video https://ufile.io/z8fsj of the problem. Notice that when I click - the animation slides up rather than slide down as I have specified.

**Comment by hayola** [comment]
@chenjiahan https://codesandbox.io/s/p2rml1l6rq

**Comment by chenjiahan** [comment]
Sorry for the late reply, i think there is no need to use `leaveAnimation` or `enterAnimation` in your case, just set `animation` to `slideUp`
