### ISSUE TITLE
inactive background

### ISSUE THREAD

**Issue by vetrslav** [chenjiahan/rodal#39]
Hi, is it possible to make screen under popup inactive when popup is active?

**Comment by chenjiahan** [comment]
what's the meaning of inactive?

**Comment by vetrslav** [comment]
I mean, that if modal window is active i am not able to intercat with other screen under popup.
Currently if modal window is open i can click buttons under modal and so on.
I want to block this ability until user close modal window.

**Comment by chenjiahan** [comment]
juse use `showMask` and `customMaskStyles`

**Comment by vetrslav** [comment]
Thanks, it was my fail, i placed modal component not in proper parent container and because of that some pert of UI was active, when modal is active.
