### ISSUE TITLE
Autofocus issue

### ISSUE THREAD

**Issue by abhishekchotaliya** [chenjiahan/rodal#41]
When Rodal is active, and you try to focus on any input element using autoFocus or `.focus()` event, it is focusing. But after a second or more, it changes focus from the input element to Rodal.

**Comment by abhishekchotaliya** [comment]
Just came to know that this issue is because of the prop: `closeOnEsc`

It is shifting focus back on Rodal so that user can press ESC key and close it.

**Comment by chenjiahan** [comment]
Yep, we can disable closeOnEsc to avoid this
