### ISSUE TITLE
A11y pressing `esc` close the modal

### ISSUE THREAD

**Issue by flexbox** [chenjiahan/rodal#44]
Pressing `esc` doesn't close the modal.
http://chenjiahan.github.io/rodal/

Tested on Firefox and Google Chrome

**Comment by JustOneJance** [comment]
yep, i tested it on Brave and Cromium, add closeOnEsc: true

**Comment by JustOneJance** [comment]
I think the library is no longer supported.
```
var defaultProps = {
    width: 400,
    height: 240,
    measure: 'px',
    visible: false,
    showMask: true,
    showCloseButton: true,
    animation: 'zoom',
    duration: 300,
    className: '',
    customStyles: {},
    customMaskStyles: {}
};
```
where closeOnEsc in props?

**Comment by chenjiahan** [comment]
@JustOneJance Did you install the latest version?

**Comment by JustOneJance** [comment]
sorry my mistake, i understood it when try add new function in your library.

**Comment by chenjiahan** [comment]
👌
