### ISSUE TITLE
id param

### ISSUE THREAD

**Issue by dy** [chenjiahan/rodal#47]
It is useful to provide id for modal element
```js
<Rodal id="preview-dialog" {...props}>{ ...content }</Rodal>
```
Would you consider such improvement?

**Comment by chenjiahan** [comment]
What is the usage scenario for the id prop?

**Comment by dy** [comment]
Mostly referring that modal via browser location.
Special handler can open it if history matches that id.

**Comment by chenjiahan** [comment]
Can you make a PR for this feature?    ^_^

**Comment by Basemsisy** [comment]
> Can you make a PR for this feature? ^_^

could you please mark this issue as closed? ^_^
