### ISSUE TITLE
Event is not available on onClose

### ISSUE THREAD

**Issue by saurabhnemade** [chenjiahan/rodal#53]
We should pass event on `onClose` function when user does `closeOnEsc` with onKeyUpEvent. I came across a case where I have modal inside modal with closeOnEsc property. The closing of inner modal closes outer modal as well. If event is available then one can stop the propagation of event to close only inner modal.

**Comment by chenjiahan** [comment]
Fixed in v1.8.1

**Comment by saurabhnemade** [comment]
Thanks. :)
