### ISSUE TITLE
React@15.0.2 does not satisfy its siblings' peerDependencies

### ISSUE THREAD

**Issue by nikkiczx** [chenjiahan/rodal#6]
Hi,

I'm trying to install this package but I am having this peerDepencies error. I can't even install the css-loader. It's giving me the same problem.
Any idea how I can install this package?

Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "rodal" "--save-dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
npm ERR! peerinvalid Peer react-mounter@1.2.0 wants react@0.14.x || 15.x.x
npm ERR! peerinvalid Peer react-skylight@0.4.0 wants react@^0.14.0 || ^15.0.1
npm ERR! peerinvalid Peer simple-react-modal@0.4.9 wants react@>=0.14 || >=15.0
npm ERR! peerinvalid Peer react-modal@1.2.1 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-modal-dialog@2.0.0 wants react@^0.14.2

Cheers,
nikki

**Comment by nikkiczx** [comment]
Uhh... Sorry, I tried running the codes and it works. But does that mean even if I see the peerinvalid errors, the installation works?

**Comment by chenjiahan** [comment]
I think it is a npm issue, maybe you should update to npm3 and try again.

**Comment by nikkiczx** [comment]
Ok. Thanks!!
