### ISSUE TITLE
Install problem with React v18

### ISSUE THREAD

**Issue by richardDobron** [chenjiahan/rodal#67]
It is not possible to install the package because `peerDependencies` does not support version ^18

package.json:
>   "peerDependencies": {
>     "react": ">= ^17.0.0"
>   },

error:
> npm ERR! Found: react@18.2.0
> npm ERR! node_modules/react
> npm ERR!   dev react@"^18.2.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@">= ^17.0.0" from rodal@2.0.0
> npm ERR! node_modules/rodal
> npm ERR!   rodal@"^2.0.0" from the root project
>

**Comment by chenjiahan** [comment]
Fixed in rodal@2.0.1
